server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/paqj/spring-boot-test/config-repo
          search-paths: config-repo/licensingservice, config-repo/organizationservice

